const TASKS = [
  {
    id: 1,
    title: "Estudar FSC",
    description: "Estudar para a prova de FSC",
    time: "morning",
    status: "in_progress",
  },
  {
    id: 2,
    title: "Tomar café da manhã",
    description: "Café reforçado antes de começar o dia",
    time: "morning",
    status: "done",
  },
  {
    id: 3,
    title: "Fazer caminhada",
    description: "Caminhada de 30 minutos no parque",
    time: "morning",
    status: "not_started",
  },
  {
    id: 4,
    title: "Organizar mesa de trabalho",
    description: "Limpar e arrumar a escrivaninha",
    time: "morning",
    status: "not_started",
  },
  {
    id: 5,
    title: "Responder e-mails",
    description: "Verificar caixa de entrada e responder clientes",
    time: "morning",
    status: "in_progress",
  },
  {
    id: 6,
    title: "Revisar tarefas do dia",
    description: "Planejar as prioridades da manhã",
    time: "night",
    status: "done",
  },

  {
    id: 7,
    title: "Ler livro",
    description: "Ler o livro técnico de arquitetura de software",
    time: "afternoon",
    status: "in_progress",
  },
  {
    id: 8,
    title: "Desenvolver componente Tasks",
    description: "Implementar a listagem e filtros de tarefas",
    time: "afternoon",
    status: "in_progress",
  },
  {
    id: 9,
    title: "Reunião de equipe",
    description: "Alinhamento semanal com o time de desenvolvimento",
    time: "afternoon",
    status: "not_started",
  },
  {
    id: 10,
    title: "Comprar suprimentos",
    description: "Ir ao mercado comprar itens do escritório",
    time: "afternoon",
    status: "not_started",
  },
  {
    id: 11,
    title: "Almoçar",
    description: "Pausa para almoço com a equipe",
    time: "afternoon",
    status: "done",
  },
  {
    id: 12,
    title: "Revisar Pull Requests",
    description: "Fazer code review das PRs abertas",
    time: "afternoon",
    status: "done",
  },

  {
    id: 13,
    title: "Treinar",
    description: "Ir para a aula de muay thai",
    time: "evening",
    status: "not_started",
  },
  {
    id: 14,
    title: "Preparar marmitas",
    description: "Cozinhar a refeição para o dia seguinte",
    time: "evening",
    status: "not_started",
  },
  {
    id: 15,
    title: "Fazer a janta",
    description: "Preparar janta leve",
    time: "evening",
    status: "in_progress",
  },
  {
    id: 16,
    title: "Assistir aula online",
    description: "Continuar o curso de React Avançado",
    time: "evening",
    status: "in_progress",
  },
  {
    id: 17,
    title: "Desconectar das telas",
    description: "Desligar computador e celular 1h antes de dormir",
    time: "evening",
    status: "done",
  },
  {
    id: 18,
    title: "Organizar mochila",
    description: "Deixar tudo pronto para amanhã",
    time: "evening",
    status: "done",
  },
]

export default TASKS
